# -*- coding: utf-8 -*-
"""iterativo_for_rendimiento.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2LZl9tnw01arjYCOBeUNUJ0WETaOKd8
"""

"""En una escuela, luego de tomar un determinado examen, es necesario calcular el promedio de notas de los alumnos de un curso
(las notas van de 0 a 10). Se necesita saber si el rendimiento ha sido elevado (el promedio es mayor a 8),
 aceptable (el promedio está comprendido entre 6 y 8) o bajo (promedio es inferior a 6).
 Desarrollar un algoritmo que resuelva este problema. Para tener en cuenta: las autoridades del colegio saben cuántos estudiantes
 del curso han rendido el examen."""

# Leer la cantidad de estudiantes
cantidad_estudiantes = int(input("Ingrese la cantidad de estudiantes: "))

# Inicializar la suma de las notas
suma_notas = 0

# Leer las notas de cada estudiante y acumularlas
for i in range(cantidad_estudiantes):
    nota = float(input(f"Ingrese la nota del estudiante {i + 1}: "))
    suma_notas += nota

# Calcular el promedio
promedio = suma_notas / cantidad_estudiantes

# Determinar el rendimiento
if promedio > 8:
    rendimiento = "elevado"
elif 6 <= promedio <= 8:
    rendimiento = "aceptable"
else:
    rendimiento = "bajo"

# Mostrar el resultado
print(f"El promedio de notas es: {promedio:.2f}")
print(f"El rendimiento del curso es: {rendimiento}")