# -*- coding: utf-8 -*-
"""iterativo_while_nros_pares.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2LZl9tnw01arjYCOBeUNUJ0WETaOKd8
"""

"""Mostrar sólo los números pares desde 0 hasta el número ingresado (input). Nota: para saber si un número es par hacer i % 2 == 0)"""

# Solicitar al usuario un número
numero = int(input("Ingrese un número: "))

# Inicializar el contador
i = 0

# Mostrar los números pares desde 0 hasta el número ingresado
while i <= numero:
    if i % 2 == 0:
        print(i)
    i += 1