# -*- coding: utf-8 -*-
"""mano_obra_pintor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2LZl9tnw01arjYCOBeUNUJ0WETaOKd8
"""

# Ingreso de Variables
Ancho= float(input("Ingrese Ek ancho de la pared en metros: "))
Alto= float(input("Ingrese el alto de la pared en metros: "))
Costoxm2= float(input("Ingrese el costo por metro2 en pesos: "))

# calcular Area de la pared
Area = Ancho * Alto

# calcular el costo total de la mano de obra
Costo_total= Area * Costoxm2

# Mostrar Valor de mano de obra
print("El costo total de la mano de obra para pintar la pared es: ", Costo_total, "pesos")